#!/bin/bash

client_id=""
client_secret=""
deviceId=""
url="https://jnuc24.jamfcloud.com"

response=$(curl --silent --location --request POST "${url}/api/oauth/token" \
 	--header "Content-Type: application/x-www-form-urlencoded" \
	--data-urlencode "client_id=${client_id}" \
	--data-urlencode "grant_type=client_credentials" \
	--data-urlencode "client_secret=${client_secret}")

accessToken=$(echo "$response" | plutil -extract access_token raw -)

getResponse=$(curl -H "Authorization: Bearer $accessToken" $url/JSSResource/mobiledevices/id/$deviceId -X GET)

echo $getResponse
