#!/bin/bash

username=""
password=""
url="https://jnuc24.jamfcloud.com"
deviceId="71"
deviceCommand=""

bearerToken=$(curl -s -u "$username":"$password" "$url"/api/v1/auth/token -X POST | plutil -extract token raw - )

postResponse=$(curl -H "Authorization: Bearer $bearerToken" $url/JSSResource/mobiledevicecommands/command/$deviceCommand/id/$deviceId -X POST)

echo $postResponse
